import { readFileSync } from "node:fs";
import { Window } from "happy-dom";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// Smoke test: verifies that the generated static HTML contains the island
// marker and that the client entry bundle can be imported and executed in a
// happy-dom environment without throwing. Full click/reactivity verification
// requires a real browser (happy-dom does not fully emulate Elur event
// delegation + signal batching).

const here = dirname(fileURLToPath(import.meta.url));

const MANAGED_GLOBALS = [
  "window", "document", "navigator", "location", "history", "screen",
  "HTMLElement", "Element", "Node", "Text", "Comment", "DocumentFragment",
  "ShadowRoot", "Event", "CustomEvent", "MutationObserver", "IntersectionObserver",
  "NodeFilter", "TreeWalker", "requestIdleCallback", "cancelIdleCallback",
];

const html = readFileSync(join(here, "dist/index.html"), "utf8");

// Verify dynamic routes generated by generateStaticParams.
for (const slug of ["hello-world", "elur-kit"]) {
  const postHtml = readFileSync(join(here, "dist/blog", slug, "index.html"), "utf8");
  if (!postHtml.includes(`<title>Post: ${slug}</title>`)) {
    throw new Error(`Dynamic page /blog/${slug} was not generated correctly`);
  }
  if (!postHtml.includes(`Slug: ${slug}`)) {
    throw new Error(`Dynamic page /blog/${slug} is missing params output`);
  }
}
console.log("✓ generateStaticParams pages verified");

// Verify route groups generate clean URLs without the group segment.
for (const marketingPath of ["pricing", "features"]) {
  const marketingHtml = readFileSync(join(here, "dist", marketingPath, "index.html"), "utf8");
  if (!marketingHtml.includes(`<h1>${marketingPath[0].toUpperCase() + marketingPath.slice(1)}</h1>`)) {
    throw new Error(`Route group page /${marketingPath} was not generated correctly`);
  }
  if (!marketingHtml.includes('class="marketing-layout"')) {
    throw new Error(`Route group page /${marketingPath} is missing the group layout`);
  }
}
console.log("✓ Route group pages verified");
const window = new Window({ url: "http://localhost:3000/" });
const g = globalThis as Record<string, unknown>;

for (const key of MANAGED_GLOBALS) {
  if (key in window) {
    g[key] = (window as unknown as Record<string, unknown>)[key];
  }
}

window.document.documentElement.innerHTML = html;

const marker = window.document.querySelector("[data-elur-island]") as HTMLElement | null;
if (!marker) {
  throw new Error("Island marker not found in generated HTML");
}
if (marker.dataset.elurJsIsland !== "LikeButton") {
  throw new Error(`Expected island "LikeButton", got "${marker.dataset.elurJsIsland}"`);
}

// Load and execute the client entry bundle. It hydrates islands on import.
await import("./dist/_elur/entry-client.js" as string);

const button = window.document.querySelector(".like-button");
if (!button) {
  throw new Error("LikeButton island not rendered after hydration");
}

console.log("✓ Hydration smoke test passed");
