import { defineConfig } from "vite";
import { resolve } from "path";

// ── Library build configuration ───────────────────────────────────────────────
//
//   npm run build:lib
//
// Produces:
//   dist/lib/index.{js,cjs}         — main entry
//   dist/lib/island/index.{js,cjs}  — island subpath
//   dist/lib/**/*.d.ts              — Type declarations (generated by tsc)

export default defineConfig({
    publicDir: false,

    build: {
        outDir: "dist/lib",
        emptyOutDir: true,
        sourcemap: true,

        lib: {
            entry: {
                index: resolve("src/index.ts"),
                "island/index": resolve("src/island/index.ts"),
                "vite/index": resolve("src/vite/index.ts"),
                "adapters/index": resolve("src/adapters/index.ts"),
                "adapters/vercel": resolve("src/adapters/vercel.ts"),
                "adapters/netlify": resolve("src/adapters/netlify.ts"),
                "adapters/bun": resolve("src/adapters/bun.ts"),
                "adapters/node": resolve("src/adapters/node.ts"),
                "action/index": resolve("src/action/index.ts"),
                "router/client": resolve("src/router/client.ts"),
                "content/index": resolve("src/content/index.ts"),
                "image/index": resolve("src/image/index.ts"),
                "image/service": resolve("src/image/service.ts"),
                "image/registry": resolve("src/image/registry.ts"),
                "seo/index": resolve("src/seo/index.ts"),
                "config/index": resolve("src/config/index.ts"),
                "manifest/index": resolve("src/manifest/index.ts"),
                "integrations/index": resolve("src/integrations/index.ts"),
                "runtime/index": resolve("src/runtime/index.ts"),
            },
            name: "NixJSKit",
            formats: ["es", "cjs"],
            fileName: (format, entryName) =>
                format === "cjs"
                    ? `${entryName}.cjs`
                    : `${entryName}.js`,
        },

        rollupOptions: {
            external: [
                /^@deijose\/nix-js(?:\/.*)?$/,
                "vite",
                "marked",
                "zod",
                "sharp",
                /^node:/,
                "module",
                "fs",
                "fs/promises",
                "path",
                "url",
                "http",
                "child_process",
            ],
            output: {
                preserveModules: false,
                globals: {
                    "@deijose/nix-js": "NixJS",
                    "vite": "Vite",
                },
                // Vite 8 deprecates inlineDynamicImports in favor of
                // codeSplitting:false, but codeSplitting:false does not support
                // multiple entry points. Keep inlineDynamicImports until the
                // upstream API supports multi-entry single-chunk output.
                inlineDynamicImports: false,
            },
        },
    },
});
