import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";
import type { IslandModule } from "./scan.js";

// --- Client entry generator ---
//
// Turns a list of scanned islands into a client entry module that imports each
// island and registers it with `hydrateIslands`. This removes the need to hand-
// maintain `entry-client.ts` as islands are added or removed.
//
// The generated file imports island default exports and passes them to
// `hydrateIslands` keyed by their registry name.

/**
 * Router options for the generated client entry (Fase 8.3).
 */
export interface RouterEntryOptions {
  /**
   * Include SPA navigation code. When `false` the generated entry is
   * hydrate-only and no router file is emitted. Default: `true`.
   */
  enabled?: boolean;
  /** Forwarded to `startClientRouter({ prefetch })`. Default: `true`. */
  prefetch?: boolean;
  /** Forwarded to `startClientRouter({ morph })` (idiomorph swap). */
  morph?: boolean;
  /** Forwarded to `startClientRouter({ loadingIndicator })`. */
  loadingIndicator?: boolean;
  /**
   * Split mode: the entry hydrates islands only and the router lives in a
   * separate generated module (`router.ts` next to the entry, emitted as its
   * own chunk). This is what lets pages without islands load only the router.
   */
  separate?: boolean;
  /** Absolute path of the generated router module when `separate` is set. */
  outFile?: string;
}

/** Options for generating the client entry module. */
export interface GenerateEntryOptions {
  /** Islands to register, from `scanIslands`. */
  islands: IslandModule[];
  /** Absolute path of the entry file to write (e.g. ".elur/entry-client.ts"). */
  outFile: string;
  /**
   * Import specifier for the kit's client island helpers.
   * Defaults to the published subpath `@elurjs/kit/island`.
   */
  hydrateImport?: string;
  /**
   * Import specifier for the kit's client router.
   * Defaults to the published subpath `@elurjs/kit/router`.
   */
  routerImport?: string;
  /**
   * Router inclusion. Omit for the legacy combined entry (router embedded).
   * With `separate: true`, a standalone router module is also generated at
   * `router.outFile`.
   */
  router?: RouterEntryOptions;
}

/** Turns a registry name into a safe JS identifier for the import binding. */
function toIdentifier(name: string, index: number): string {
  const cleaned = name.replace(/[^a-zA-Z0-9_$]/g, "_");
  return /^[a-zA-Z_$]/.test(cleaned) ? `${cleaned}_${index}` : `_${cleaned}_${index}`;
}

/**
 * Source for the standalone router module emitted in split builds. Router
 * options are baked in so the public module takes no arguments.
 */
export function buildRouterEntrySource(
  routerImport = "@elurjs/kit/router",
  options: Omit<RouterEntryOptions, "enabled" | "separate" | "outFile"> = {},
): string {
  const opts: Record<string, boolean> = {};
  if (options.prefetch === false) opts.prefetch = false;
  if (options.morph === true) opts.morph = true;
  if (options.loadingIndicator === true) opts.loadingIndicator = true;
  const args = Object.keys(opts).length > 0 ? JSON.stringify(opts) : "";
  return `// AUTO-GENERATED by @elurjs/kit. Do not edit.
import { startClientRouter } from ${JSON.stringify(routerImport)};

startClientRouter(${args});
`;
}

/**
 * Serializes the startClientRouter options embedded in a combined entry.
 * Only non-default flags are emitted to keep the generated code minimal.
 */
function routerCallArgs(router?: RouterEntryOptions): string {
  const opts: Record<string, boolean> = {};
  if (router?.prefetch === false) opts.prefetch = false;
  if (router?.morph === true) opts.morph = true;
  if (router?.loadingIndicator === true) opts.loadingIndicator = true;
  return Object.keys(opts).length > 0 ? JSON.stringify(opts) : "";
}

/** Builds the source code of the client entry module. */
export function buildEntrySource(
  islands: IslandModule[],
  outFile: string,
  hydrateImport = "@elurjs/kit/island",
  routerImport = "@elurjs/kit/router",
  router?: RouterEntryOptions,
): string {
  const bindings = islands.map((island, i) => ({
    ident: toIdentifier(island.name, i),
    name: island.name,
    // Relative import specifier from the entry file to the island module.
    spec: toImportSpecifier(outFile, island.filePath),
  }));

  // Lazy registry: each island is loaded on-demand via dynamic import().
  // This enables code-splitting — islands not on the current page (or not yet
  // triggered by their directive) stay out of the initial bundle.
  //
  // The registry maps island name → discriminated lazy loader `{ load }`.
  // hydrateIslands() awaits `entry.load()` before hydrating, so the first
  // paint only needs the small entry chunk + the islands on the page. The
  // discriminated form lets the hydrator tell eager components from lazy
  // loaders without executing a probe.
  const registryLines = bindings
    .map((b) => `  ${JSON.stringify(b.name)}: { load: () => import(${JSON.stringify(b.spec)}).then(m => m.default) },`)
    .join("\n");

  const islandHydration = registryLines
    ? `const registry = {
${registryLines}
};
const hydrate = () => hydrateIslands(registry);
// Islands inside persisted nodes must not be disposed across navigations.
// The router announces the survivors in the elur:before-render detail; the
// DOM query fallback covers hosts that dispatch it without detail.
const cleanup = (persisted) =>
  cleanupHydratedIslands({
    except: persisted ?? document.querySelectorAll("[data-elur-persist]"),
  });
let sawBeforeRender = false;

// Hydrate right after parse: module scripts are deferred, so this already
// runs once the DOM is ready. Directives schedule themselves inside
// hydrateIslands — "load"/"only" run immediately (real Astro semantics),
// "idle"/"visible" keep their deferred scheduling.
hydrate();

// The router dispatches elur:before-render BEFORE swapping #app: islands are
// disposed while still attached (Fase A2), except persisted subtrees.
document.addEventListener("elur:before-render", (event) => {
  sawBeforeRender = true;
  cleanup(event.detail?.persisted);
});

// Re-hydrate after SPA navigations.
document.addEventListener("elur:rendered", () => {
  // Compat fallback: hosts that only dispatch elur:rendered (streaming swap
  // script, hand-rolled integrations) still need the cleanup pass.
  if (!sawBeforeRender) cleanup();
  sawBeforeRender = false;
  hydrate();
});

// Vite HMR: when an island module (or the entry itself) updates, dispose the
// current islands and re-hydrate from the updated modules — the registry's
// dynamic import() resolves to the fresh modules, so no full page reload is
// needed (progressive enhancement, audit §10.2 / §12.2).
if (import.meta.hot) {
  import.meta.hot.accept(() => {
    cleanupHydratedIslands();
    hydrateIslands(registry);
  });
}`
    : "";

  // The router is embedded in the entry unless a separate chunk was
  // requested (split builds) or the router is disabled outright.
  const embedRouter = router ? router.enabled !== false && !router.separate : true;

  return `// AUTO-GENERATED by @elurjs/kit. Do not edit.
${embedRouter ? `import { startClientRouter } from ${JSON.stringify(routerImport)};\n` : ""}import { hydrateIslands, cleanupHydratedIslands } from ${JSON.stringify(hydrateImport)};
${embedRouter ? `\nstartClientRouter(${routerCallArgs(router)});\n` : ""}${islandHydration}
`;
}

/** Computes a POSIX-style relative import specifier between two files. */
function toImportSpecifier(fromFile: string, toFile: string): string {
  let spec = relative(dirname(fromFile), toFile).split(sep).join("/");
  if (!spec.startsWith(".")) spec = `./${spec}`;
  return spec;
}

/**
 * Generates and writes the client entry module for the given islands. When
 * `options.router.separate` is set (and the router is enabled), a standalone
 * router module is written alongside it (default: `router.ts` next to the
 * entry — bundle it as a second input to emit `/_elur/router.js`).
 *
 * @param options Generation options.
 * @returns The absolute path of the written entry file.
 */
export async function generateClientEntry(
  options: GenerateEntryOptions,
): Promise<string> {
  const source = buildEntrySource(
    options.islands,
    options.outFile,
    options.hydrateImport,
    options.routerImport,
    options.router,
  );
  await mkdir(dirname(options.outFile), { recursive: true });
  await writeFile(options.outFile, source, "utf8");

  // Always emit the router module whenever router options were provided —
  // even in combined mode or with the router disabled — so a two-input user
  // config (`.elur/router.ts` as second input) never breaks on a missing
  // file. In combined mode the file is simply never emitted as a page script.
  if (options.router) {
    const routerFile =
      options.router.outFile ?? join(dirname(options.outFile), "router.ts");
    const routerSource =
      options.router.enabled === false
        ? `// AUTO-GENERATED by @elurjs/kit. Do not edit.\n// router.enabled: false — intentionally empty.\nexport {};\n`
        : buildRouterEntrySource(options.routerImport ?? "@elurjs/kit/router", options.router);
    await writeFile(routerFile, routerSource, "utf8");
  }
  return options.outFile;
}
